language: python
os: linux

matrix:
  include:
    - language: generic
      os: osx
      before_install:
        - brew update
        - brew upgrade python
        - pip3 install virtualenv
        - virtualenv env -p python3
        - source env/bin/activate
        - python -V
    - language: python
      os: linux
      python: 3.6

script: "./scripts/build-unix.sh"

deploy:
  provider: releases
  api_key:
    secure: f8aJvEKPRq2L4GpLmZYn57S8YdDxdgLhdgig65DxpEB8OdwhiKlbsJt8JoTYfz3au5ocwvlvmnV+3HjZUiKcqjRudUCi87F73J1woGF+a/Az6h2dLGWeFb31pwVxRFJs32iLL0EMTvtIdEVjrUOt1DqP3vPAuEEzdQboZj6eZZg=
  file_glob: true
  file: "binary/divio-*"
  skip_cleanup: true
  overwrite: true
  draft: true
  name: $TRAVIS_TAG
  tag: $TRAVIS_TAG
  on:
    repo: divio/divio-cli
    tags: true
